# Generated by Django 3.1.1 on 2020-09-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/%Y/%m/%d', verbose_name='Archivo'),
        ),
    ]
